task_manager/statuses/urls.py
from django.urls import path
from . import views

app_name = 'statuses'

urlpatterns = [
    path('', views.StatusListView.as_view(), name='list'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from task_manager.views import HomeView
from task_manager.users.views import LogIn, LogOut
# from . import views


def home(request):
    return HttpResponse("Halo")


urlpatterns = [
    path('admin/', admin.site.urls),
    # rollback подключен успешно
    # path('', views.index, name='index'),   
    path('', HomeView.as_view(), name='home'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('login/', LogIn.as_view(), name='login'),
    path('logout/', LogOut.as_view(), name='logout'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

task_manager/statuses/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    name = models.CharField("Имя", max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']  # Имя поля должно совпадать с демонстрационным проектом  # noqa: E501

task_manager/statuses/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import StatusForm
from .models import Status


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/status_list.html'
    context_object_name = 'statuses'


class StatusCreateView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/status_form.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно создан!')

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/status_form.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _("Статус успешно изменен!")


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'statuses/status_confirm_delete.html'
    success_url = reverse_lazy('statuses:list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        name = self.object.name
        try:
            self.object.delete()
            messages.success(request, _("Статус успешно удален!").format(name=name))  # noqa: E501
        except ProtectedError:
            messages.error(request, _("Невозможно удалить статус.").format(name=name))  # noqa: E501
        return redirect(self.success_url)

task_manager/statuses/templates/statuses/status_confirm_delete.html
<!--http://127.0.0.1:8000/statuses/id/delete/-->

{% extends "base.html" %}

{% block title %}Удаление статуса{% endblock %}

{% block content %}
<div class="container py-5 text-center">
    <h1>Удаление статуса</h1>
    <p>Вы уверены, что хотите удалить статус "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да, удалить</button>
        <a href="{% url 'statuses:list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

task_manager/statuses/templates/statuses/status_form.html
<!--http://127.0.0.1:8000/statuses/create/-->
<!--http://127.0.0.1:8000/statuses/id/update/-->

{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}{% if object %}Редактировать{% else %}Создать{% endif %} статус{% endblock %}

{% block content %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column justify-content-center">
    <main class="px-3 text-center">
        <h1>{% if object %}Редактировать{% else %}Создать{% endif %} статус</h1>
        <form method="post" class="text-start mx-auto p-4 border rounded shadow-sm bg-dark" style="max-width: 400px;">
            {% csrf_token %}
            {% bootstrap_form form layout='vertical' %}
            <button type="submit" class="btn btn-primary mt-3 w-100">{% if object %}Изменить{% else %}Создать{% endif %}</button>
        </form>
    </main>
</div>
{% endblock %}

task_manager/statuses/templates/statuses/status_list.html
<!--http://127.0.0.1:8000/statuses/-->

{% extends "base.html" %}

{% if messages %}
    {% for message in messages %}
        <div>{{ message }}</div>
    {% endfor %}
{% endif %}

{% block title %}Список статусов{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Список статусов</h1>
        <a href="{% url 'statuses:create' %}" class="btn btn-primary">Создать статус</a>
    </div>

    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя статуса</th>
                <th>Дата создания</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for status in statuses %}
            <tr>
                <td>{{ status.id }}</td>
                <td>{{ status.name }}</td>
                <td>{{ status.created|date:"d.m.Y H:i" }}</td>
                <td>
                    <a href="{% url 'statuses:update' status.pk %}" class="btn btn-sm btn-warning">Изменить</a>
                    <a href="{% url 'statuses:delete' status.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Статусов пока нет.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}