task_manager/labels/urls.py
from django.urls import path
from .views import LabelListView, LabelCreateView, LabelUpdateView, LabelDeleteView  # noqa: E501

app_name = 'labels'

urlpatterns = [
    path('', LabelListView.as_view(), name='list'),
    path('create/', LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LabelDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from task_manager.views import HomeView
from task_manager.users.views import LogIn, LogOut
# from . import views


def home(request):
    return HttpResponse("Halo")


urlpatterns = [
    path('admin/', admin.site.urls),
    # rollback подключен успешно
    # path('', views.index, name='index'),   
    path('', HomeView.as_view(), name='home'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('login/', LogIn.as_view(), name='login'),
    path('logout/', LogOut.as_view(), name='logout'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

task_manager/labels/models.py
from django.db import models

# Create your models here.


class Label(models.Model):
    name = models.CharField("Имя", max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/labels/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Label

# Create your views here.


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/label_list.html'
    context_object_name = 'labels'


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    fields = ['name']
    template_name = 'labels/label_form.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно создана!')


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    fields = ['name']
    template_name = 'labels/label_form.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно изменена!')


class LabelDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = 'labels/label_confirm_delete.html'
    success_url = reverse_lazy('labels:list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.tasks.exists():
            messages.error(request, _("Невозможно удалить метку."))
            return redirect('labels:list')
        self.object.delete()
        messages.success(request, _("Метка успешно удалена!"))
        return redirect(self.success_url)

task_manager/labels/templates/labels/label_confirm_delete.html
<!--<h1>http://127.0.0.1:8000/labels/delete/</h1>-->

{% extends "base.html" %}

{% block title %}Удаление метки{% endblock %}

{% block content %}
<div class="container py-5 text-center">
    <h1>Удаление метки</h1>
    <p>Вы уверены, что хотите удалить метку "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да, удалить</button>
        <a href="{% url 'labels:list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

task_manager/labels/templates/labels/label_form.html
<!--<h1>http://127.0.0.1:8000/labels/create/</h1>-->
<!--<h1>http://127.0.0.1:8000/labels/id/update/</h1>-->

{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
    {% if object %}Изменение метки{% else %}Создать метку{% endif %}
{% endblock %}

{% block content %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column justify-content-center">
    <main class="px-3 text-center">
        <h1>
            {% if object %}Изменение метки{% else %}Создать метку{% endif %}
        </h1>
        <form method="post"
              class="text-start mx-auto p-4 border rounded shadow-sm bg-dark"
              style="max-width: 400px;">
            {% csrf_token %}
            {% bootstrap_form form layout='vertical' %}
            <button type="submit"
                    class="btn btn-primary mt-3 w-100">
                {% if object %}Изменить{% else %}Создать{% endif %}
            </button>
        </form>
    </main>
</div>
{% endblock %}

task_manager/labels/templates/labels/label_list.html
<!--<h1>http://127.0.0.1:8000/labels/</h1>-->
{% extends "base.html" %}

{% if messages %}
    {% for message in messages %}
        <div>{{ message }}</div>
    {% endfor %}
{% endif %}

{% block title %}Список меток{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Список меток</h1>
        <a href="{% url 'labels:create' %}" class="btn btn-primary">
            Создать метку
        </a>
    </div>

    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя метки</th>
                <th>Дата создания</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for label in labels %}
            <tr>
                <td>{{ label.id }}</td>
                <td>{{ label.name }}</td>
                <td>{{ label.created|date:"d.m.Y H:i" }}</td>
                <td>
                    <a href="{% url 'labels:update' label.pk %}"
                       class="btn btn-sm btn-warning">
                        Изменить
                    </a>
                    <a href="{% url 'labels:delete' label.pk %}"
                       class="btn btn-sm btn-danger">
                        Удалить
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Меток пока нет.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}