task_manager/urls.py
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from task_manager.views import HomeView
from task_manager.users.views import LogIn, LogOut
# from . import views


def home(request):
    return HttpResponse("Halo")


urlpatterns = [
    path('admin/', admin.site.urls),
    # rollback подключен успешно
    # path('', views.index, name='index'),   
    path('', HomeView.as_view(), name='home'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('login/', LogIn.as_view(), name='login'),
    path('logout/', LogOut.as_view(), name='logout'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

task_manager/users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserDeleteView

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

task_manager/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

# Create your models here.


class User(AbstractUser):
    first_name = models.CharField(
        max_length=150,
        blank=False,
        verbose_name=_('Имя')
    )
    last_name = models.CharField(
        max_length=150,
        blank=False,
        verbose_name=_('Фамилия')
    )
    USERNAME_FIELD = 'username'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

task_manager/users/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "password1", "password2"]  # Имя поля должно совпадать с демонстрационным проектом  # noqa: E501

task_manager/users/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import UserForm

User = get_user_model()


class UserListView(ListView):
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'users'


class UserCreateView(CreateView):
    model = User
    form_class = UserForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        messages.success(self.request, _(
            "Пользователь успешно зарегистрирован!"))
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:user_list')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj != request.user and not request.user.is_superuser:
            messages.error(request, _(
                "У вас нет прав для изменения другого пользователя."))
            return redirect('users:user_list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, _("Пользователь успешно изменен!"))
        return super().form_valid(form)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        return form


class UserDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/user_confirm_delete.html'
    success_url = reverse_lazy('users:user_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user and not request.user.is_superuser:
            messages.error(request, _(
                "У вас нет прав для изменения другого пользователя."))
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(request, _("Пользователь успешно удален!"))
        except ProtectedError:
            messages.error(request, _(
                "Нельзя удалить пользователя, пока у него есть задачи."))
        return redirect(self.success_url)


class LogIn(LoginView):
    template_name = 'registration/login.html'
    success_url = reverse_lazy('home')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['username'].label = 'Имя пользователя'
        form.fields['password'].label = 'Пароль'
        return form
    
    def form_valid(self, form):
        messages.success(self.request, _("Вы залогинены!"))
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('home')


class LogOut(LogoutView):
    next_page = reverse_lazy('home')
    
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, _("Вы разлогинены!"))
        return super().dispatch(request, *args, **kwargs)

task_manager/users/templates/users/user_confirm_delete.html
<!--http://127.0.0.1:8000/users/id/delete/-->

{% extends "base.html" %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<div class="container py-5">
    <h1>Удалить пользователя "{{ object.username }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да, удалить</button>
        <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

task_manager/users/templates/users/user_form.html
<!--http://127.0.0.1:8000/users/id/update/-->
<!--http://127.0.0.1:8000/users/create/-->

{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column justify-content-center">
    <main class="px-3 text-center">
        <h1>
            {% if form.instance.pk %}
                Изменить пользователя
            {% else %}
                Регистрация
            {% endif %}
        </h1>
        <form method="post" class="text-start mx-auto p-4 border rounded shadow-sm bg-dark" style="max-width: 400px;">
            {% csrf_token %}
            {% bootstrap_form form layout='vertical' %}
            <button type="submit" class="btn btn-primary mt-3 w-100">
                {% if form.instance.pk %}
                    Изменить
                {% else %}
                    Зарегистрировать
                {% endif %}
            </button>
        </form>
    </main>
</div>
{% endblock %}

task_manager/users/templates/users/user_list.html
<!--http://127.0.0.1:8000/users/-->

{% extends "base.html" %}

{% block title %}Список пользователей{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Список пользователей</h1>
        <a href="{% url 'users:user_create' %}" class="btn btn-primary">Создать нового</a>
    </div>

    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя пользователя</th>
                <th>Полное имя</th>
                <th>Дата создания</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.date_joined|date:"d.m.Y H:i" }}</td>
                <td>
                    <a href="{% url 'users:user_update' user.pk %}" class="btn btn-sm btn-warning">Изменить</a>
                    <a href="{% url 'users:user_delete' user.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}